# Site
name: "加拿大种菜笔记"
title: "加拿大种菜笔记"
description: "加拿大种菜笔记 - 一个加拿大种菜爱好者的个人博客"
logo: 'assets/images/logo.jpg'
favicon: 'assets/images/logo.jpg'
baseurl: ''
#google_analytics: 'UA-1'
#disqus: 'site'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  sal:
    name: pzgarden
    display_name: pzgarden
    #gravatar: 
    #email: 
    #web: 
    #twitter: 
    description: "一个加拿大种菜爱好者"


# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
#adsense: "disabled"
#adsense-data-ad-client: "ca-pub-3412143450191416"
#adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
